server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: college-management-system
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/college_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: 86400000 # 24 hours

logging:
  level:
    com.college: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
